### ISSUE TITLE
How to find the overlap region？

### ISSUE THREAD

**Issue by wangzz15** [fabiopoiesi/dip#11]
Dear author,
thanks for your excellent work. 
I'm a beginner in the filed of Point Cloud Registration. I still don't know how to find the overlap region. The red points seems to be randomly selected in the source code. Could you please give some advice?
![image](https://user-images.githubusercontent.com/56377924/136695792-e4dae6e1-6d91-4520-a369-e71c9c5630ca.png)

**Comment by fabiopoiesi** [comment]
The overlap region can be found using knn, setting k=1, on the point clouds transformed with their respective transformations.
Both the point clouds should be in the same reference system to apply knn.
You should also apply a distance threshold on the nn point.

In the supplementary material of [SmoothNet paper](https://arxiv.org/pdf/1811.06879.pdf), this process is explained in detail.
In DIP I used the data pre-processed in this paper.
However, it is something that can be code up in minutes.

The red points are indeed randomly sampled, using farthest point sampling, from the cyan points.

**Comment by wenli4313** [comment]
I have been studying the DIP paper recently, and I would like to ask you some questions. If you see the message, you can contact me on wechat:zwl577729391, thank you very much.
