### ISSUE TITLE
Question about the Paper

### ISSUE THREAD

**Issue by yuvalH9** [fabiopoiesi/dip#14]
Hi @fabiopoiesi ,
I really enjoyed reading your paper and thanks for supplying your code.
After reading the paper I have some question which are still unclear to me.
1) In the bottleneck part you explain how you find potential matched points within the corresponding patches using `alpha` and `alpha'` that their corresponding feature cross some threshold.
It is not clear to me when you use this idea in the training pipeline, or you just mentioned that for general analysis?

2) In Equ (6), it is not clear to me how you define the sets `C_pos` and `C_neg` and how you generate the feature vectors `f`.
Does C_pos are a set of matching patches with their network output?

Thanks
Yuval

**Comment by fabiopoiesi** [comment]
Hi @yuvalH9,

thanks for your interest in the paper.

1. As you mentioned, I just made these observations for sake of analysis and to motivate the thresholding steps done afterwards. I am not using `alpha` and `alpha'` in the actual computation of the descriptors.
2. `f` is the descriptors the network outputs. `C_pos` is a pair of descriptors created from two corresponding patches. These corresponding patches are extracted from two point clouds that have an overlap greater than 30%. `C_neg` are all the other descriptors within a batch (of course excluding `C_pos`).

I hope this helps.

**Comment by yuvalH9** [comment]
@fabiopoiesi  thanks!
 it helps a lot indeed!

Another unclear issue, I'm still not sure where you are using  `p_rho` in your training pipeline.
You are ignoring patches with `rho` less than that threshold when you are calculating the Triplet loss?
The pdf of `rho` is estimated from all the patches in a single batch?

Yuval

**Comment by fabiopoiesi** [comment]
Sorry for the late reply. I totally missed it.
`p_rho` is used to filter out patches during registration, see Tab. V of the paper where different values are used.
