### ISSUE TITLE
Problem of no points inside the kernel size

### ISSUE THREAD

**Issue by epicjung** [fabiopoiesi/dip#15]
Hi, I am really appreciated with your works! 

I am just wondering how you dealt with the situation where no points or fewer than 3 points are inside the LRF kernel in lpf.py:

https://github.com/fabiopoiesi/dip/blob/6b72d5c370793d91efd3560c9f1819f731b34da4/lrf.py#L21

This results in complex numbers in xp, yp, zp.

https://github.com/fabiopoiesi/dip/blob/6b72d5c370793d91efd3560c9f1819f731b34da4/lrf.py#L45

![image](https://user-images.githubusercontent.com/38877956/161504112-7589b5a3-6ec2-40e8-ab0c-85973549a56f.png)

How did you resolve this problem?

As a solution, putting in zero xyz values to the patch would be a problem. Any ideas?

Thank you very much!

**Comment by fabiopoiesi** [comment]
This is actually a problem, you could either discard this patch or repeat these three points by adding some little Gaussian noise.
