### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by epicjung** [fabiopoiesi/dip#16]
Hi, very appreciate the work you have done!

I am just curious about the license of this work. MIT? BSD? 

Any plan to announce how you are going to distribute this work?

Thank you so much

**Comment by davideboscaini** [comment]
Ciao, buona visita per oggi! Per la licenza dovremo capire quale scegliere.
C'è molta differenza tra l'una e l'altra. Tecnicamente senza licenza le
persone non potrebbero nemmeno usare il codice.
D

Il Ven 15 Apr 2022, 03:53 epicjung ***@***.***> ha scritto:

**Comment by fabiopoiesi** [comment]
Hi, we haven't made a decision about the license for this work, this is the reason why we did not mentioned any license yet.
We will think about it and let you know.
Thanks for asking.

**Comment by epicjung** [comment]
Thank you :)
