### ISSUE TITLE
the result is not sa good as presented

### ISSUE THREAD

**Issue by yaoyishen** [fabiopoiesi/dip#2]
the result we got using 'python demo_3dmatch.py' is not so good as presented in the paper.The cups on tabel is not aligned.

**Comment by fabiopoiesi** [comment]
This is what I obtained rerunning the code.
![ScreenCapture_2020-11-09-07-10-06](https://user-images.githubusercontent.com/17005352/98505948-b096b580-225a-11eb-9522-d275f7c61327.png)

This is similar to the screenshot in the README page. 
As it is written in the README, the demo uses RANSAC for registration, which is not deterministic. It depends on the sampling. Results may differ slightly.
If you need to refine the registration and obtain a more consistent registration, I suggest you use a step of ICP after the RANSAC estimation. For this you can follow this procedure [link](http://www.open3d.org/docs/release/tutorial/reconstruction_system/refine_registration.html).

**Comment by yaoyishen** [comment]
ok, I've got it.I still need a ICP to refine the result after the RANSAC estimation

**Comment by wenli4313** [comment]
> the result we got using 'python demo_3dmatch.py' is not so good as presented in the paper.The cups on tabel is not aligned.
Hello,how do you get the final_chkpt.pth,thank you!

**Comment by wenli4313** [comment]
I have been studying the DIP paper recently, and I would like to ask you some questions. If you see the message, you can contact me on wechat:zwl577729391, thank you very much.
