### ISSUE TITLE
AttributeError: module 'open3d' has no attribute 'registration'

### ISSUE THREAD

**Issue by houyongkuo** [fabiopoiesi/dip#5]
Hi, thanks for your interesting work.
When I preprocessed 3DMatch training data, I got the error "AttributeError: module 'open3d' has no attribute 'registration' ".

from  https://github.com/intel-isl/Open3D/issues/2951
**o3d.pipelines.**registration.compute_fpfh_feature(pcd).

It seems that now it is under pipelines based on the new documentation http://www.open3d.org/docs/release/python_api/open3d.pipelines.html

So in preprocess_3dmatch_correspondences_train.py, we can use:

```
 result =o3d.pipelines.registration.registration_icp(pcd1, pcd2, .02, np.eye(4),
                                                           o3d.pipelines.registration.TransformationEstimationPointToPoint())
```

Thanks!
Best wishes!

**Comment by fabiopoiesi** [comment]
Hi,
Yes this is the issue. 
By adding pipelines it will solve it.

**Comment by wenli4313** [comment]
I have been studying the DIP paper recently, and I would like to ask you some questions. If you see the message, you can contact me on wechat:zwl577729391, thank you very much.
