### ISSUE TITLE
AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'select_down_sample'

### ISSUE THREAD

**Issue by houyongkuo** [fabiopoiesi/dip#7]
Hi!
When I run "preprocess_3dmatch_lrf_train.py", I got the error "AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'select_down_sample'".

Using
```
            # select only corresponding points
            pcd1_corr = pcd1.select_by_index(corrs[:, 0])
            pcd2_corr = pcd2.select_by_index(corrs[:, 1])
```
will fix the error.

Thanks.
Best wishes!

**Comment by fabiopoiesi** [comment]
Accepted your pull request!
This has to do with the new version of open3d.
