### ISSUE TITLE
preprocessed data

### ISSUE THREAD

**Issue by wenli4313** [fabiopoiesi/dip#9]
Hi, I really appreciate your work on point cloud registration .The link of preprocessed data has been unable to be opened. Is there any other way or can you send it to me.Thank you very much.

**Comment by fabiopoiesi** [comment]
Thanks for letting me know.
I'll try to sort this issue out by tomorrow.
Best regards

**Comment by wenli4313** [comment]
Could you please send it to my email directly? 577729391@qq.com

**Comment by fabiopoiesi** [comment]
Please try now.
